/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class seda_util_MDWUtil */

#ifndef _Included_seda_util_MDWUtil
#define _Included_seda_util_MDWUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     seda_util_MDWUtil
 * Method:    currentTimeUsec
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_seda_util_MDWUtil_currentTimeUsec
  (JNIEnv *, jclass);

/*
 * Class:     seda_util_MDWUtil
 * Method:    usleep
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_seda_util_MDWUtil_usleep
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
