/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class seda_util_StatsGatherer */

#ifndef _Included_seda_util_StatsGatherer
#define _Included_seda_util_StatsGatherer
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
