/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class seda_util_Tracer */

#ifndef _Included_seda_util_Tracer
#define _Included_seda_util_Tracer
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class seda_util_Tracer_traceVal */

#ifndef _Included_seda_util_Tracer_traceVal
#define _Included_seda_util_Tracer_traceVal
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
