#!/bin/sh

# Front-end script to run Sandstorm

LD_LIBRARY_PATH=../nbio/bin:$LD_LIBRARY_PATH; echo $LD_LIBRARY_PATH; java -ms128M -mx1024M -cp ../sandstorm/bin:../nbio/bin:../util/bin seda.sandStorm.main.Main $*
